### ISSUE TITLE
documentation wrong or confusing

### ISSUE THREAD

**Issue by fcollman** [cajal/LabelOps#2]
says 
`
   neighborhood = op.generate_neighborhood(vertices)
`
but code has 
`def generate_neighborhood(triangles, num_vertices=None):
`
I assume that triangles is what you want and not vertices.

**Comment by Cpapa97** [comment]
Yes that's exactly correct, it was meant to be triangles not vertices. The README has been fixed.

**Comment by eywalker** [comment]
@Cpapa97 Let's verify the fix and then close this issue.
